version: "3.8"

services:
  php-build:
    image: "php:${PHP_VERSION:-7.1}-cli"
    command: ["sh", "/srv/php-lib/.docker/setup.sh"]
    stdin_open: true
    volumes:
      - ./:/srv/php-lib
      - ${HOME}/.aws/credentials:/root/.aws/credentials
